
class BotStates:
    BOT_INIT = 0
    BOT_MENU = 1
    BOT_USER_USERNAME = 2
    BOT_USER_ID = 3
    BOT_USER_HASH = 4
    BOT_USER_PHONE = 5
    BOT_USERS_LIST = 6
    BOT_USER_SELECTED = 7
    BOT_SCRAPE = 8
    BOT_SCRAPE_SELECT = 9
    BOT_SCRAPE_STOP = 10


class ThreadResponse:
    INVALID_CREDS = 0
    INVALID_CODE = 0
